name: AsureFishing
version: '1.0'
author: SaintQd
main: org.saintqd.asurefishing.AsureFishing
api-version: '26.2'
description: AsureFishing Plugin
dependencies:
  server:
    AsureLib:
      load: BEFORE
      required: true
    MythicMobs:
      load: BEFORE
      required: true
    WorldGuard:
      load: BEFORE
      required: true