name: AsureFishing
version: 1.0
author: SaintQd
main: org.saintqd.asurefishing.AsureFishing
api-version: 26.2
depend: [AsureLib, MythicMobs, WorldGuard]
permissions:
  asurefishing.admin:
    description: Access to admin commands.
    default: op